pod 'MQTTKit', :git => 'https://github.com/mobile-web-messaging/MQTTKit.git'
pod 'NKOColorPickerView'

# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Ghost' do

end

target 'GhostTests' do

end

